export const GOOGLEWITHREQ = 'GOOGLEWITHREQ';
export const GoogleWithRES = 'GoogleWithRES';
export const GOOGLEWITHREJ = 'GOOGLEWITHREJ';

export const ADDDOCDATAREQ = "ADDDOCDATAREQ"
export const ADDDOCDATARES = "ADDDOCDATARES"
export const ADDDOCDATAREJ = "ADDDOCDATAREJ"

export const GETDOCDATAREQ = "GETDOCDATAREQ"
export const GETDOCDATARES = "GETDOCDATARES"
export const GETDOCDATAREJ = "GETDOCDATAREJ"

export const DELETDATAREQ = "DELETDATAREQ"
export const DELETDATARES = "DELETDATARES"
export const DELETDATAREJ = "DELETDATAREJ"